<?php
function blacksilver_get_allowed_tags() {
	$blacksilver_general_allowed_tags = array(
		'a'          => array(
			'id'     => true,
			'class'  => true,
			'href'   => true,
			'rel'    => true,
			'rev'    => true,
			'name'   => true,
			'target' => true,
		),
		'form'       => array(
			'class'          => true,
			'id'             => true,
			'action'         => true,
			'accept'         => true,
			'accept-charset' => true,
			'enctype'        => true,
			'method'         => true,
			'name'           => true,
			'target'         => true,
		),
		'input'      => array(
			'class'   => array(),
			'id'      => array(),
			'type'    => array(),
			'name'    => array(),
			'value'   => array(),
			'checked' => array(),
		),
		'select'     => array(
			'class' => array(),
			'id'    => array(),
			'type'  => array(),
			'name'  => array(),
			'value' => array(),
		),
		'section'    => array(
			'id'       => true,
			'class'    => true,
			'align'    => true,
			'dir'      => true,
			'lang'     => true,
			'xml:lang' => true,
		),
		'svg'        => array(
			'id'      => true,
			'class'   => true,
			'width'   => true,
			'height'  => true,
			'viewbox' => true,
			'align'   => true,
			'xmlns'   => true,
		),
		'g'          => array(
			'fill'              => true,
			'stroke'            => true,
			'stroke'            => true,
			'stroke-linejoin'   => true,
			'stroke-miterlimit' => true,
		),
		'circle'     => array(
			'class' => true,
			'cx'    => true,
			'cy'    => true,
			'r'     => true,
		),
		'path'       => array(
			'class' => true,
			'd'     => true,
		),
		'abbr'       => array(),
		'acronym'    => array(),
		'b'          => array(),
		'bdo'        => array(
			'dir' => true,
		),
		'big'        => array(),
		'blockquote' => array(
			'cite'     => true,
			'lang'     => true,
			'xml:lang' => true,
		),
		'br'         => array(),
		'caption'    => array(
			'align' => true,
		),
		'div'        => array(
			'id'         => true,
			'style'      => true,
			'class'      => true,
			'data-color' => true,
			'align'      => true,
			'dir'        => true,
			'lang'       => true,
			'xml:lang'   => true,
		),
		'dl'         => array(),
		'dt'         => array(),
		'em'         => array(),
		'h1'         => array(
			'class' => array(),
			'id'    => array(),
			'align' => true,
		),
		'h2'         => array(
			'class' => array(),
			'id'    => array(),
			'align' => true,
		),
		'h3'         => array(
			'class' => array(),
			'id'    => array(),
			'align' => true,
		),
		'h4'         => array(
			'class' => array(),
			'id'    => array(),
			'align' => true,
		),
		'h5'         => array(
			'class' => array(),
			'id'    => array(),
			'align' => true,
		),
		'h6'         => array(
			'class' => array(),
			'id'    => array(),
			'align' => true,
		),
		'hr'         => array(
			'align'   => true,
			'noshade' => true,
			'size'    => true,
			'width'   => true,
		),
		'i'          => array(
			'id'    => true,
			'class' => true,
		),
		'img'        => array(
			'id'          => true,
			'class'       => true,
			'alt'         => true,
			'data-src'    => true,
			'data-srcset' => true,
			'srcset'      => true,
			'sizes'       => true,
			'align'       => true,
			'border'      => true,
			'height'      => true,
			'hspace'      => true,
			'longdesc'    => true,
			'vspace'      => true,
			'src'         => true,
			'usemap'      => true,
			'width'       => true,
		),
		'label'      => array(
			'for' => true,
		),
		'li'         => array(
			'data-id'       => true,
			'data-title'    => true,
			'data-position' => true,
			'class'         => true,
			'align'         => true,
			'value'         => true,
		),
		'p'          => array(
			'id'       => true,
			'class'    => true,
			'align'    => true,
			'dir'      => true,
			'lang'     => true,
			'xml:lang' => true,
		),
		'pre'        => array(
			'width' => true,
		),
		'q'          => array(
			'cite' => true,
		),
		'span'       => array(
			'dir'      => true,
			'id'       => true,
			'class'    => true,
			'align'    => true,
			'lang'     => true,
			'xml:lang' => true,
		),
		'small'      => array(),
		'strike'     => array(),
		'strong'     => array(),
		'title'      => array(),
		'u'          => array(),
		'ul'         => array(
			'type'  => true,
			'id'    => true,
			'class' => true,
		),
		'ol'         => array(
			'id'       => true,
			'class'    => true,
			'start'    => true,
			'type'     => true,
			'reversed' => true,
		),
	);

	return $blacksilver_general_allowed_tags;
}
function blacksilver_country_list( $output_type = 'select', $selected = '' ) {
	$countries    = array(
		'none' => 'Choose Country',
		'AF'   => 'Afghanistan',
		'AX'   => 'Aland Islands',
		'AL'   => 'Albania',
		'DZ'   => 'Algeria',
		'AS'   => 'American Samoa',
		'AD'   => 'Andorra',
		'AO'   => 'Angola',
		'AI'   => 'Anguilla',
		'AQ'   => 'Antarctica',
		'AG'   => 'Antigua And Barbuda',
		'AR'   => 'Argentina',
		'AM'   => 'Armenia',
		'AW'   => 'Aruba',
		'AU'   => 'Australia',
		'AT'   => 'Austria',
		'AZ'   => 'Azerbaijan',
		'BS'   => 'Bahamas',
		'BH'   => 'Bahrain',
		'BD'   => 'Bangladesh',
		'BB'   => 'Barbados',
		'BY'   => 'Belarus',
		'BE'   => 'Belgium',
		'BZ'   => 'Belize',
		'BJ'   => 'Benin',
		'BM'   => 'Bermuda',
		'BT'   => 'Bhutan',
		'BO'   => 'Bolivia',
		'BA'   => 'Bosnia And Herzegovina',
		'BW'   => 'Botswana',
		'BV'   => 'Bouvet Island',
		'BR'   => 'Brazil',
		'IO'   => 'British Indian Ocean Territory',
		'BN'   => 'Brunei Darussalam',
		'BG'   => 'Bulgaria',
		'BF'   => 'Burkina Faso',
		'BI'   => 'Burundi',
		'KH'   => 'Cambodia',
		'CM'   => 'Cameroon',
		'CA'   => 'Canada',
		'CV'   => 'Cape Verde',
		'KY'   => 'Cayman Islands',
		'CF'   => 'Central African Republic',
		'TD'   => 'Chad',
		'CL'   => 'Chile',
		'CN'   => 'China',
		'CX'   => 'Christmas Island',
		'CC'   => 'Cocos (Keeling) Islands',
		'CO'   => 'Colombia',
		'KM'   => 'Comoros',
		'CG'   => 'Congo',
		'CD'   => 'Congo, Democratic Republic',
		'CK'   => 'Cook Islands',
		'CR'   => 'Costa Rica',
		'CI'   => 'Cote D\'Ivoire',
		'HR'   => 'Croatia',
		'CU'   => 'Cuba',
		'CY'   => 'Cyprus',
		'CZ'   => 'Czech Republic',
		'DK'   => 'Denmark',
		'DJ'   => 'Djibouti',
		'DM'   => 'Dominica',
		'DO'   => 'Dominican Republic',
		'EC'   => 'Ecuador',
		'EG'   => 'Egypt',
		'SV'   => 'El Salvador',
		'GQ'   => 'Equatorial Guinea',
		'ER'   => 'Eritrea',
		'EE'   => 'Estonia',
		'ET'   => 'Ethiopia',
		'FK'   => 'Falkland Islands (Malvinas)',
		'FO'   => 'Faroe Islands',
		'FJ'   => 'Fiji',
		'FI'   => 'Finland',
		'FR'   => 'France',
		'GF'   => 'French Guiana',
		'PF'   => 'French Polynesia',
		'TF'   => 'French Southern Territories',
		'GA'   => 'Gabon',
		'GM'   => 'Gambia',
		'GE'   => 'Georgia',
		'DE'   => 'Germany',
		'GH'   => 'Ghana',
		'GI'   => 'Gibraltar',
		'GR'   => 'Greece',
		'GL'   => 'Greenland',
		'GD'   => 'Grenada',
		'GP'   => 'Guadeloupe',
		'GU'   => 'Guam',
		'GT'   => 'Guatemala',
		'GG'   => 'Guernsey',
		'GN'   => 'Guinea',
		'GW'   => 'Guinea-Bissau',
		'GY'   => 'Guyana',
		'HT'   => 'Haiti',
		'HM'   => 'Heard Island & Mcdonald Islands',
		'VA'   => 'Holy See (Vatican City State)',
		'HN'   => 'Honduras',
		'HK'   => 'Hong Kong',
		'HU'   => 'Hungary',
		'IS'   => 'Iceland',
		'IN'   => 'India',
		'ID'   => 'Indonesia',
		'IR'   => 'Iran, Islamic Republic Of',
		'IQ'   => 'Iraq',
		'IE'   => 'Ireland',
		'IM'   => 'Isle Of Man',
		'IL'   => 'Israel',
		'IT'   => 'Italy',
		'JM'   => 'Jamaica',
		'JP'   => 'Japan',
		'JE'   => 'Jersey',
		'JO'   => 'Jordan',
		'KZ'   => 'Kazakhstan',
		'KE'   => 'Kenya',
		'KI'   => 'Kiribati',
		'KR'   => 'Korea',
		'KW'   => 'Kuwait',
		'KG'   => 'Kyrgyzstan',
		'LA'   => 'Lao People\'s Democratic Republic',
		'LV'   => 'Latvia',
		'LB'   => 'Lebanon',
		'LS'   => 'Lesotho',
		'LR'   => 'Liberia',
		'LY'   => 'Libyan Arab Jamahiriya',
		'LI'   => 'Liechtenstein',
		'LT'   => 'Lithuania',
		'LU'   => 'Luxembourg',
		'MO'   => 'Macao',
		'MK'   => 'Macedonia',
		'MG'   => 'Madagascar',
		'MW'   => 'Malawi',
		'MY'   => 'Malaysia',
		'MV'   => 'Maldives',
		'ML'   => 'Mali',
		'MT'   => 'Malta',
		'MH'   => 'Marshall Islands',
		'MQ'   => 'Martinique',
		'MR'   => 'Mauritania',
		'MU'   => 'Mauritius',
		'YT'   => 'Mayotte',
		'MX'   => 'Mexico',
		'FM'   => 'Micronesia, Federated States Of',
		'MD'   => 'Moldova',
		'MC'   => 'Monaco',
		'MN'   => 'Mongolia',
		'ME'   => 'Montenegro',
		'MS'   => 'Montserrat',
		'MA'   => 'Morocco',
		'MZ'   => 'Mozambique',
		'MM'   => 'Myanmar',
		'NA'   => 'Namibia',
		'NR'   => 'Nauru',
		'NP'   => 'Nepal',
		'NL'   => 'Netherlands',
		'AN'   => 'Netherlands Antilles',
		'NC'   => 'New Caledonia',
		'NZ'   => 'New Zealand',
		'NI'   => 'Nicaragua',
		'NE'   => 'Niger',
		'NG'   => 'Nigeria',
		'NU'   => 'Niue',
		'NF'   => 'Norfolk Island',
		'MP'   => 'Northern Mariana Islands',
		'NO'   => 'Norway',
		'OM'   => 'Oman',
		'PK'   => 'Pakistan',
		'PW'   => 'Palau',
		'PS'   => 'Palestinian Territory, Occupied',
		'PA'   => 'Panama',
		'PG'   => 'Papua New Guinea',
		'PY'   => 'Paraguay',
		'PE'   => 'Peru',
		'PH'   => 'Philippines',
		'PN'   => 'Pitcairn',
		'PL'   => 'Poland',
		'PT'   => 'Portugal',
		'PR'   => 'Puerto Rico',
		'QA'   => 'Qatar',
		'RE'   => 'Reunion',
		'RO'   => 'Romania',
		'RU'   => 'Russian Federation',
		'RW'   => 'Rwanda',
		'BL'   => 'Saint Barthelemy',
		'SH'   => 'Saint Helena',
		'KN'   => 'Saint Kitts And Nevis',
		'LC'   => 'Saint Lucia',
		'MF'   => 'Saint Martin',
		'PM'   => 'Saint Pierre And Miquelon',
		'VC'   => 'Saint Vincent And Grenadines',
		'WS'   => 'Samoa',
		'SM'   => 'San Marino',
		'ST'   => 'Sao Tome And Principe',
		'SA'   => 'Saudi Arabia',
		'SN'   => 'Senegal',
		'RS'   => 'Serbia',
		'SC'   => 'Seychelles',
		'SL'   => 'Sierra Leone',
		'SG'   => 'Singapore',
		'SK'   => 'Slovakia',
		'SI'   => 'Slovenia',
		'SB'   => 'Solomon Islands',
		'SO'   => 'Somalia',
		'ZA'   => 'South Africa',
		'GS'   => 'South Georgia And Sandwich Isl.',
		'ES'   => 'Spain',
		'LK'   => 'Sri Lanka',
		'SD'   => 'Sudan',
		'SR'   => 'Suriname',
		'SJ'   => 'Svalbard And Jan Mayen',
		'SZ'   => 'Swaziland',
		'SE'   => 'Sweden',
		'CH'   => 'Switzerland',
		'SY'   => 'Syrian Arab Republic',
		'TW'   => 'Taiwan',
		'TJ'   => 'Tajikistan',
		'TZ'   => 'Tanzania',
		'TH'   => 'Thailand',
		'TL'   => 'Timor-Leste',
		'TG'   => 'Togo',
		'TK'   => 'Tokelau',
		'TO'   => 'Tonga',
		'TT'   => 'Trinidad And Tobago',
		'TN'   => 'Tunisia',
		'TR'   => 'Turkey',
		'TM'   => 'Turkmenistan',
		'TC'   => 'Turks And Caicos Islands',
		'TV'   => 'Tuvalu',
		'UG'   => 'Uganda',
		'UA'   => 'Ukraine',
		'AE'   => 'United Arab Emirates',
		'GB'   => 'United Kingdom',
		'US'   => 'United States',
		'UM'   => 'United States Outlying Islands',
		'UY'   => 'Uruguay',
		'UZ'   => 'Uzbekistan',
		'VU'   => 'Vanuatu',
		'VE'   => 'Venezuela',
		'VN'   => 'Viet Nam',
		'VG'   => 'Virgin Islands, British',
		'VI'   => 'Virgin Islands, U.S.',
		'WF'   => 'Wallis And Futuna',
		'EH'   => 'Western Sahara',
		'YE'   => 'Yemen',
		'ZM'   => 'Zambia',
		'ZW'   => 'Zimbabwe',
	);
	$country_list = false;

	if ( 'select' === $output_type ) {
		$country_list = '';
		foreach ( $countries as $key => $option ) {
			if ( $selected === $key ) {
				$country_selected = 'selected="selected"';
			} else {
				$country_selected = '';
			}
			$country_list .= '<option value="' . esc_attr( $key ) . '" ' . $country_selected . '>' . esc_attr( $option ) . '</option>';
		}
	}
	if ( 'display' === $output_type ) {
		if ( array_key_exists( $selected, $countries ) ) {
			$country_list = $countries[ $selected ];
		}
	}
	return $country_list;
}
function blacksilver_set_fontawesome( $fallback_icon, $the_icon, $get_css_code ) {
	if ( $get_css_code ) {
		$fontawesome_icons = array(
			'fa-glass'                => '\\f000',
			'fa-music'                => '\\f001',
			'fa-search'               => '\\f002',
			'fa-envelope-o'           => '\\f003',
			'fa-heart'                => '\\f004',
			'fa-star'                 => '\\f005',
			'fa-star-o'               => '\\f006',
			'fa-user'                 => '\\f007',
			'fa-film'                 => '\\f008',
			'fa-th-large'             => '\\f009',
			'fa-th'                   => '\\f00a',
			'fa-th-list'              => '\\f00b',
			'fa-check'                => '\\f00c',
			'fa-times'                => '\\f00d',
			'fa-search-plus'          => '\\f00e',
			'fa-search-minus'         => '\\f010',
			'fa-power-off'            => '\\f011',
			'fa-signal'               => '\\f012',
			'fa-cog'                  => '\\f013',
			'fa-trash-o'              => '\\f014',
			'fa-home'                 => '\\f015',
			'fa-file-o'               => '\\f016',
			'fa-clock-o'              => '\\f017',
			'fa-road'                 => '\\f018',
			'fa-download'             => '\\f019',
			'fa-arrow-circle-o-down'  => '\\f01a',
			'fa-arrow-circle-o-up'    => '\\f01b',
			'fa-inbox'                => '\\f01c',
			'fa-play-circle-o'        => '\\f01d',
			'fa-repeat'               => '\\f01e',
			'fa-refresh'              => '\\f021',
			'fa-list-alt'             => '\\f022',
			'fa-lock'                 => '\\f023',
			'fa-flag'                 => '\\f024',
			'fa-headphones'           => '\\f025',
			'fa-volume-off'           => '\\f026',
			'fa-volume-down'          => '\\f027',
			'fa-volume-up'            => '\\f028',
			'fa-qrcode'               => '\\f029',
			'fa-barcode'              => '\\f02a',
			'fa-tag'                  => '\\f02b',
			'fa-tags'                 => '\\f02c',
			'fa-book'                 => '\\f02d',
			'fa-bookmark'             => '\\f02e',
			'fa-print'                => '\\f02f',
			'fa-camera'               => '\\f030',
			'fa-font'                 => '\\f031',
			'fa-bold'                 => '\\f032',
			'fa-italic'               => '\\f033',
			'fa-text-height'          => '\\f034',
			'fa-text-width'           => '\\f035',
			'fa-align-left'           => '\\f036',
			'fa-align-center'         => '\\f037',
			'fa-align-right'          => '\\f038',
			'fa-align-justify'        => '\\f039',
			'fa-list'                 => '\\f03a',
			'fa-outdent'              => '\\f03b',
			'fa-indent'               => '\\f03c',
			'fa-video-camera'         => '\\f03d',
			'fa-picture-o'            => '\\f03e',
			'fa-pencil'               => '\\f040',
			'fa-map-marker'           => '\\f041',
			'fa-adjust'               => '\\f042',
			'fa-tint'                 => '\\f043',
			'fa-pencil-square-o'      => '\\f044',
			'fa-share-square-o'       => '\\f045',
			'fa-check-square-o'       => '\\f046',
			'fa-arrows'               => '\\f047',
			'fa-step-backward'        => '\\f048',
			'fa-fast-backward'        => '\\f049',
			'fa-backward'             => '\\f04a',
			'fa-play'                 => '\\f04b',
			'fa-pause'                => '\\f04c',
			'fa-stop'                 => '\\f04d',
			'fa-forward'              => '\\f04e',
			'fa-fast-forward'         => '\\f050',
			'fa-step-forward'         => '\\f051',
			'fa-eject'                => '\\f052',
			'fa-chevron-left'         => '\\f053',
			'fa-chevron-right'        => '\\f054',
			'fa-plus-circle'          => '\\f055',
			'fa-minus-circle'         => '\\f056',
			'fa-times-circle'         => '\\f057',
			'fa-check-circle'         => '\\f058',
			'fa-question-circle'      => '\\f059',
			'fa-info-circle'          => '\\f05a',
			'fa-crosshairs'           => '\\f05b',
			'fa-times-circle-o'       => '\\f05c',
			'fa-check-circle-o'       => '\\f05d',
			'fa-ban'                  => '\\f05e',
			'fa-arrow-left'           => '\\f060',
			'fa-arrow-right'          => '\\f061',
			'fa-arrow-up'             => '\\f062',
			'fa-arrow-down'           => '\\f063',
			'fa-share'                => '\\f064',
			'fa-expand'               => '\\f065',
			'fa-compress'             => '\\f066',
			'fa-plus'                 => '\\f067',
			'fa-minus'                => '\\f068',
			'fa-asterisk'             => '\\f069',
			'fa-exclamation-circle'   => '\\f06a',
			'fa-gift'                 => '\\f06b',
			'fa-leaf'                 => '\\f06c',
			'fa-fire'                 => '\\f06d',
			'fa-eye'                  => '\\f06e',
			'fa-eye-slash'            => '\\f070',
			'fa-exclamation-triangle' => '\\f071',
			'fa-plane'                => '\\f072',
			'fa-calendar'             => '\\f073',
			'fa-random'               => '\\f074',
			'fa-comment'              => '\\f075',
			'fa-magnet'               => '\\f076',
			'fa-chevron-up'           => '\\f077',
			'fa-chevron-down'         => '\\f078',
			'fa-retweet'              => '\\f079',
			'fa-shopping-cart'        => '\\f07a',
			'fa-folder'               => '\\f07b',
			'fa-folder-open'          => '\\f07c',
			'fa-arrows-v'             => '\\f07d',
			'fa-arrows-h'             => '\\f07e',
			'fa-bar-chart-o'          => '\\f080',
			'fa-twitter-square'       => '\\f081',
			'fa-facebook-square'      => '\\f082',
			'fa-camera-retro'         => '\\f083',
			'fa-key'                  => '\\f084',
			'fa-cogs'                 => '\\f085',
			'fa-comments'             => '\\f086',
			'fa-thumbs-o-up'          => '\\f087',
			'fa-thumbs-o-down'        => '\\f088',
			'fa-star-half'            => '\\f089',
			'fa-heart-o'              => '\\f08a',
			'fa-sign-out'             => '\\f08b',
			'fa-linkedin-square'      => '\\f08c',
			'fa-thumb-tack'           => '\\f08d',
			'fa-external-link'        => '\\f08e',
			'fa-sign-in'              => '\\f090',
			'fa-trophy'               => '\\f091',
			'fa-github-square'        => '\\f092',
			'fa-upload'               => '\\f093',
			'fa-lemon-o'              => '\\f094',
			'fa-phone'                => '\\f095',
			'fa-square-o'             => '\\f096',
			'fa-bookmark-o'           => '\\f097',
			'fa-phone-square'         => '\\f098',
			'fa-twitter'              => '\\f099',
			'fa-facebook'             => '\\f09a',
			'fa-github'               => '\\f09b',
			'fa-unlock'               => '\\f09c',
			'fa-credit-card'          => '\\f09d',
			'fa-rss'                  => '\\f09e',
			'fa-hdd-o'                => '\\f0a0',
			'fa-bullhorn'             => '\\f0a1',
			'fa-bell'                 => '\\f0f3',
			'fa-certificate'          => '\\f0a3',
			'fa-hand-o-right'         => '\\f0a4',
			'fa-hand-o-left'          => '\\f0a5',
			'fa-hand-o-up'            => '\\f0a6',
			'fa-hand-o-down'          => '\\f0a7',
			'fa-arrow-circle-left'    => '\\f0a8',
			'fa-arrow-circle-right'   => '\\f0a9',
			'fa-arrow-circle-up'      => '\\f0aa',
			'fa-arrow-circle-down'    => '\\f0ab',
			'fa-globe'                => '\\f0ac',
			'fa-wrench'               => '\\f0ad',
			'fa-tasks'                => '\\f0ae',
			'fa-filter'               => '\\f0b0',
			'fa-briefcase'            => '\\f0b1',
			'fa-arrows-alt'           => '\\f0b2',
			'fa-users'                => '\\f0c0',
			'fa-link'                 => '\\f0c1',
			'fa-cloud'                => '\\f0c2',
			'fa-flask'                => '\\f0c3',
			'fa-scissors'             => '\\f0c4',
			'fa-files-o'              => '\\f0c5',
			'fa-paperclip'            => '\\f0c6',
			'fa-floppy-o'             => '\\f0c7',
			'fa-square'               => '\\f0c8',
			'fa-bars'                 => '\\f0c9',
			'fa-list-ul'              => '\\f0ca',
			'fa-list-ol'              => '\\f0cb',
			'fa-strikethrough'        => '\\f0cc',
			'fa-underline'            => '\\f0cd',
			'fa-table'                => '\\f0ce',
			'fa-magic'                => '\\f0d0',
			'fa-truck'                => '\\f0d1',
			'fa-pinterest'            => '\\f0d2',
			'fa-pinterest-square'     => '\\f0d3',
			'fa-google-plus-square'   => '\\f0d4',
			'fa-google-plus'          => '\\f0d5',
			'fa-money'                => '\\f0d6',
			'fa-caret-down'           => '\\f0d7',
			'fa-caret-up'             => '\\f0d8',
			'fa-caret-left'           => '\\f0d9',
			'fa-caret-right'          => '\\f0da',
			'fa-columns'              => '\\f0db',
			'fa-sort'                 => '\\f0dc',
			'fa-sort-desc'            => '\\f0dd',
			'fa-sort-asc'             => '\\f0de',
			'fa-envelope'             => '\\f0e0',
			'fa-linkedin'             => '\\f0e1',
			'fa-undo'                 => '\\f0e2',
			'fa-gavel'                => '\\f0e3',
			'fa-tachometer'           => '\\f0e4',
			'fa-comment-o'            => '\\f0e5',
			'fa-comments-o'           => '\\f0e6',
			'fa-bolt'                 => '\\f0e7',
			'fa-sitemap'              => '\\f0e8',
			'fa-umbrella'             => '\\f0e9',
			'fa-clipboard'            => '\\f0ea',
			'fa-lightbulb-o'          => '\\f0eb',
			'fa-exchange'             => '\\f0ec',
			'fa-cloud-download'       => '\\f0ed',
			'fa-cloud-upload'         => '\\f0ee',
			'fa-user-md'              => '\\f0f0',
			'fa-stethoscope'          => '\\f0f1',
			'fa-suitcase'             => '\\f0f2',
			'fa-bell-o'               => '\\f0a2',
			'fa-coffee'               => '\\f0f4',
			'fa-cutlery'              => '\\f0f5',
			'fa-file-text-o'          => '\\f0f6',
			'fa-building-o'           => '\\f0f7',
			'fa-hospital-o'           => '\\f0f8',
			'fa-ambulance'            => '\\f0f9',
			'fa-medkit'               => '\\f0fa',
			'fa-fighter-jet'          => '\\f0fb',
			'fa-beer'                 => '\\f0fc',
			'fa-h-square'             => '\\f0fd',
			'fa-plus-square'          => '\\f0fe',
			'fa-angle-double-left'    => '\\f100',
			'fa-angle-double-right'   => '\\f101',
			'fa-angle-double-up'      => '\\f102',
			'fa-angle-double-down'    => '\\f103',
			'fa-angle-left'           => '\\f104',
			'fa-angle-right'          => '\\f105',
			'fa-angle-up'             => '\\f106',
			'fa-angle-down'           => '\\f107',
			'fa-desktop'              => '\\f108',
			'fa-laptop'               => '\\f109',
			'fa-tablet'               => '\\f10a',
			'fa-mobile'               => '\\f10b',
			'fa-circle-o'             => '\\f10c',
			'fa-quote-left'           => '\\f10d',
			'fa-quote-right'          => '\\f10e',
			'fa-spinner'              => '\\f110',
			'fa-circle'               => '\\f111',
			'fa-reply'                => '\\f112',
			'fa-github-alt'           => '\\f113',
			'fa-folder-o'             => '\\f114',
			'fa-folder-open-o'        => '\\f115',
			'fa-smile-o'              => '\\f118',
			'fa-frown-o'              => '\\f119',
			'fa-meh-o'                => '\\f11a',
			'fa-gamepad'              => '\\f11b',
			'fa-keyboard-o'           => '\\f11c',
			'fa-flag-o'               => '\\f11d',
			'fa-flag-checkered'       => '\\f11e',
			'fa-terminal'             => '\\f120',
			'fa-code'                 => '\\f121',
			'fa-reply-all'            => '\\f122',
			'fa-star-half-o'          => '\\f123',
			'fa-location-arrow'       => '\\f124',
			'fa-crop'                 => '\\f125',
			'fa-code-fork'            => '\\f126',
			'fa-chain-broken'         => '\\f127',
			'fa-question'             => '\\f128',
			'fa-info'                 => '\\f129',
			'fa-exclamation'          => '\\f12a',
			'fa-superscript'          => '\\f12b',
			'fa-subscript'            => '\\f12c',
			'fa-eraser'               => '\\f12d',
			'fa-puzzle-piece'         => '\\f12e',
			'fa-microphone'           => '\\f130',
			'fa-microphone-slash'     => '\\f131',
			'fa-shield'               => '\\f132',
			'fa-calendar-o'           => '\\f133',
			'fa-fire-extinguisher'    => '\\f134',
			'fa-rocket'               => '\\f135',
			'fa-maxcdn'               => '\\f136',
			'fa-chevron-circle-left'  => '\\f137',
			'fa-chevron-circle-right' => '\\f138',
			'fa-chevron-circle-up'    => '\\f139',
			'fa-chevron-circle-down'  => '\\f13a',
			'fa-html5'                => '\\f13b',
			'fa-css3'                 => '\\f13c',
			'fa-anchor'               => '\\f13d',
			'fa-unlock-alt'           => '\\f13e',
			'fa-bullseye'             => '\\f140',
			'fa-ellipsis-h'           => '\\f141',
			'fa-ellipsis-v'           => '\\f142',
			'fa-rss-square'           => '\\f143',
			'fa-play-circle'          => '\\f144',
			'fa-ticket'               => '\\f145',
			'fa-minus-square'         => '\\f146',
			'fa-minus-square-o'       => '\\f147',
			'fa-level-up'             => '\\f148',
			'fa-level-down'           => '\\f149',
			'fa-check-square'         => '\\f14a',
			'fa-pencil-square'        => '\\f14b',
			'fa-external-link-square' => '\\f14c',
			'fa-share-square'         => '\\f14d',
			'fa-compass'              => '\\f14e',
			'fa-caret-square-o-down'  => '\\f150',
			'fa-caret-square-o-up'    => '\\f151',
			'fa-caret-square-o-right' => '\\f152',
			'fa-eur'                  => '\\f153',
			'fa-gbp'                  => '\\f154',
			'fa-usd'                  => '\\f155',
			'fa-inr'                  => '\\f156',
			'fa-jpy'                  => '\\f157',
			'fa-rub'                  => '\\f158',
			'fa-krw'                  => '\\f159',
			'fa-btc'                  => '\\f15a',
			'fa-file'                 => '\\f15b',
			'fa-file-text'            => '\\f15c',
			'fa-sort-alpha-asc'       => '\\f15d',
			'fa-sort-alpha-desc'      => '\\f15e',
			'fa-sort-amount-asc'      => '\\f160',
			'fa-sort-amount-desc'     => '\\f161',
			'fa-sort-numeric-asc'     => '\\f162',
			'fa-sort-numeric-desc'    => '\\f163',
			'fa-thumbs-up'            => '\\f164',
			'fa-thumbs-down'          => '\\f165',
			'fa-youtube-square'       => '\\f166',
			'fa-youtube'              => '\\f167',
			'fa-xing'                 => '\\f168',
			'fa-xing-square'          => '\\f169',
			'fa-youtube-play'         => '\\f16a',
			'fa-dropbox'              => '\\f16b',
			'fa-stack-overflow'       => '\\f16c',
			'fa-instagram'            => '\\f16d',
			'fa-flickr'               => '\\f16e',
			'fa-adn'                  => '\\f170',
			'fa-bitbucket'            => '\\f171',
			'fa-bitbucket-square'     => '\\f172',
			'fa-tumblr'               => '\\f173',
			'fa-tumblr-square'        => '\\f174',
			'fa-long-arrow-down'      => '\\f175',
			'fa-long-arrow-up'        => '\\f176',
			'fa-long-arrow-left'      => '\\f177',
			'fa-long-arrow-right'     => '\\f178',
			'fa-apple'                => '\\f179',
			'fa-windows'              => '\\f17a',
			'fa-android'              => '\\f17b',
			'fa-linux'                => '\\f17c',
			'fa-dribbble'             => '\\f17d',
			'fa-skype'                => '\\f17e',
			'fa-foursquare'           => '\\f180',
			'fa-trello'               => '\\f181',
			'fa-female'               => '\\f182',
			'fa-male'                 => '\\f183',
			'fa-gittip'               => '\\f184',
			'fa-sun-o'                => '\\f185',
			'fa-moon-o'               => '\\f186',
			'fa-archive'              => '\\f187',
			'fa-bug'                  => '\\f188',
			'fa-vk'                   => '\\f189',
			'fa-weibo'                => '\\f18a',
			'fa-renren'               => '\\f18b',
			'fa-pagelines'            => '\\f18c',
			'fa-stack-exchange'       => '\\f18d',
			'fa-arrow-circle-o-right' => '\\f18e',
			'fa-arrow-circle-o-left'  => '\\f190',
			'fa-caret-square-o-left'  => '\\f191',
			'fa-dot-circle-o'         => '\\f192',
			'fa-wheelchair'           => '\\f193',
			'fa-vimeo-square'         => '\\f194',
			'fa-try'                  => '\\f195',
			'fa-plus-square-o'        => '\\f196',
			'fa-space-shuttle'        => '\\f197',
			'fa-slack'                => '\\f198',
			'fa-envelope-square'      => '\\f199',
			'fa-wordpress'            => '\\f19a',
			'fa-openid'               => '\\f19b',
			'fa-university'           => '\\f19c',
			'fa-graduation-cap'       => '\\f19d',
			'fa-yahoo'                => '\\f19e',
			'fa-google'               => '\\f1a0',
			'fa-reddit'               => '\\f1a1',
			'fa-reddit-square'        => '\\f1a2',
			'fa-stumbleupon-circle'   => '\\f1a3',
			'fa-stumbleupon'          => '\\f1a4',
			'fa-delicious'            => '\\f1a5',
			'fa-digg'                 => '\\f1a6',
			'fa-pied-piper'           => '\\f1a7',
			'fa-pied-piper-alt'       => '\\f1a8',
			'fa-drupal'               => '\\f1a9',
			'fa-joomla'               => '\\f1aa',
			'fa-language'             => '\\f1ab',
			'fa-fax'                  => '\\f1ac',
			'fa-building'             => '\\f1ad',
			'fa-child'                => '\\f1ae',
			'fa-paw'                  => '\\f1b0',
			'fa-spoon'                => '\\f1b1',
			'fa-cube'                 => '\\f1b2',
			'fa-cubes'                => '\\f1b3',
			'fa-behance'              => '\\f1b4',
			'fa-behance-square'       => '\\f1b5',
			'fa-steam'                => '\\f1b6',
			'fa-steam-square'         => '\\f1b7',
			'fa-recycle'              => '\\f1b8',
			'fa-car'                  => '\\f1b9',
			'fa-taxi'                 => '\\f1ba',
			'fa-tree'                 => '\\f1bb',
			'fa-spotify'              => '\\f1bc',
			'fa-deviantart'           => '\\f1bd',
			'fa-soundcloud'           => '\\f1be',
			'fa-database'             => '\\f1c0',
			'fa-file-pdf-o'           => '\\f1c1',
			'fa-file-word-o'          => '\\f1c2',
			'fa-file-excel-o'         => '\\f1c3',
			'fa-file-powerpoint-o'    => '\\f1c4',
			'fa-file-image-o'         => '\\f1c5',
			'fa-file-archive-o'       => '\\f1c6',
			'fa-file-audio-o'         => '\\f1c7',
			'fa-file-video-o'         => '\\f1c8',
			'fa-file-code-o'          => '\\f1c9',
			'fa-vine'                 => '\\f1ca',
			'fa-codepen'              => '\\f1cb',
			'fa-jsfiddle'             => '\\f1cc',
			'fa-life-ring'            => '\\f1cd',
			'fa-circle-o-notch'       => '\\f1ce',
			'fa-rebel'                => '\\f1d0',
			'fa-empire'               => '\\f1d1',
			'fa-git-square'           => '\\f1d2',
			'fa-git'                  => '\\f1d3',
			'fa-hacker-news'          => '\\f1d4',
			'fa-tencent-weibo'        => '\\f1d5',
			'fa-qq'                   => '\\f1d6',
			'fa-weixin'               => '\\f1d7',
			'fa-paper-plane'          => '\\f1d8',
			'fa-paper-plane-o'        => '\\f1d9',
			'fa-history'              => '\\f1da',
			'fa-circle-thin'          => '\\f1db',
			'fa-header'               => '\\f1dc',
			'fa-paragraph'            => '\\f1dd',
			'fa-sliders'              => '\\f1de',
			'fa-share-alt'            => '\\f1e0',
			'fa-share-alt-square'     => '\\f1e1',
			'fa-bomb'                 => '\\f1e2',
		);

		if ( 'fa fa-blank' !== $the_icon && ! empty( $the_icon ) && isset( $the_icon ) ) {
			$two_piece_fallback_array = explode( ' ', $fallback_icon );
			$css_fallback_name        = $two_piece_fallback_array[1];
			$two_piece_given_array    = explode( ' ', $the_icon );
			$css_given_name           = $two_piece_given_array[1];

			if ( array_key_exists( $css_given_name, $fontawesome_icons ) ) {
				return $fontawesome_icons[ $css_given_name ];
			} else {
				return $fontawesome_icons[ $css_fallback_name ];
			}
		}
	} else {
		if ( 'fa fa-blank' !== $the_icon && ! empty( $the_icon ) && isset( $the_icon ) ) {
			return $the_icon;
		} else {
			return $fallback_icon;
		}
	}
}

function blacksilver_get_css_classes( $get_class ) {
	$style['accent_color_classes'] = '.entry-content > a:hover,
	.entry-content p > a:hover,
	.project-details a,
	.post-single-tags a:hover,
	.post-meta-category a:hover,
	.post-single-meta a:hover,
	.post-navigation a:hover,
	.entry-post-title h2 a:hover,
	.comment-reply-title small a,
	.header-shopping-cart a:hover,
	#gridblock-filter-select i,
	.entry-content .blogpost_readmore a,
	.pricing-table .pricing_highlight .pricing-price,
	#wp-calendar tfoot td#prev a,
	#wp-calendar tfoot td#next a,
	.footer-widget .widget_nav_menu a:hover,
	.entry-content .faq-toggle-link:before,
	.mtheme-knowledgebase-archive ul li:before,
	.like-vote-icon,
	.readmore-service a:hover,
	.work-details h4 a:hover,
	.service-content h4 a:hover,
	.postsummarywrap a:hover,
	.toggle-menu-list li a:hover,
	#footer a:hover,
	.nav-previous a:hover,
	.nav-next a:hover,
	.nav-lightbox a:hover,
	.entry-content .entry-post-title h2 a:hover,
	.woocommerce .mtheme-woocommerce-description-wrap a.add_to_cart_button:hover,
	.woocommerce ul.products li.product h3 a:hover,
	.woocommerce-page ul.products li.product h3 a:hover,
	.woocommerce .woocommerce-info a,
	.tagcloud a:hover,
	#footer .tagcloud a:hover,
	#events_list .recentpost_info .recentpost_title:hover,
	#recentposts_list .recentpost_info .recentpost_title:hover,
	#popularposts_list .popularpost_info .popularpost_title:hover,
	.mtheme-events-carousel .slideshow-box-title a:hover,
	.woocommerce .product_meta a:hover,
	.entry-content .service-content h4 a:hover,
	.slideshow-box-content .slideshow-box-title a:hover,
	.project-details-link a:hover,
	.entry-content .text-is-dark a:hover,
	.event-icon-sep,
	.header-is-opaque .social-sharing-toggle:hover i,
	.header-is-opaque.fullscreen-slide-dark .social-sharing-toggle:hover i,
	.header-is-opaque .stickymenu-zone .social-sharing-toggle:hover i,
	.cart-elements .cart-title:hover,
	.theme-is-light .vertical-menu ul.mtree li.mtree-open > a,
	.work-details .arrow-link, .entry-blog-contents-wrap .arrow-link,
	.entry-blog-contents-wrap .theme-hover-arrow,
	.entry-blog-contents-wrap .theme-hover-arrow:hover,
	.entry-blog-contents-wrap .theme-hover-arrow:focus,
	.entry-blog-contents-wrap .theme-hover-arrow:hover:after,
	.entry-blog-contents-wrap .theme-hover-arrow:focus:after';

	$style['page_titles'] = '
	.work-details h4,
	.work-details h4 a,
	.client-company a:hover,
	.portfolio-share li a:hover,
	.min-search .icon-search:hover,
	.entry-content .entry-post-title h2 a,
	ul.gridblock-listbox .work-details h4 a:hover,
	.header-shopping-cart:hover i,
	.client-position,
	.shortcode-time-counter-block h4,
	.time-count-data,
	.woocommerce table td,
	.imagebox-content-above .imagebox-title,
	.imagebox-content-below .imagebox-title,
	.imagebox-content-above .imagebox-box .textlink,
	.text-is-bright .imagebox-content-above .imagebox-box .textlink,
	.social-sharing-toggle:hover i,
	h1,
	h2,
	h3,
	h4,
	h5,
	h6,
	.entry-content h1,
	.entry-content h2,
	.entry-content h3,
	.entry-content h4,
	.entry-content h5,
	.entry-content h6,
	.entry-content .slideshow-box-info h3.photocard-subtitle,
	.entry-content .gridblock-blog-parallax h3.photocard-subtitle,
	.proofing-client-title,
	#respond .must-log-in > a,
	.slideshow-box-title a,
	.slideshow-box-title,
	.entry-content .slideshow-box-title h2 a:hover,
	.callout h2.callout-title,
	ul.vertical_images .vertical-images-title,
	.entry-content .portfolio-details-section-inner h2,
	.entry-content .portfolio-details-section-inner h4,
	.entry-content .portfolio-details-section-inner .project-details-link h4,
	.entry-content .portfolio-details-section-inner .project-details-link h4 a,
	.project-info h4,
	.project-details-link i,
	.project-details-link h4 a,
	.service-content h4 a,
	.entry-content .mtheme-404-wrap h4,
	.mtheme-404-wrap #searchbutton i,
	.mtheme-404-wrap .mtheme-404-error-message1,
	.mtheme-404-wrap .mtheme-404-error-message2,
	.woocommerce ul.products li.product h3,
	.woocommerce-page ul.products li.product h3,
	.woocommerce .product-name,
	.woocommerce .product-name a,
	.woocommerce ul.products li.product .woocommerce-loop-category__title,
	.woocommerce ul.products li.product .woocommerce-loop-product__title,
	.woocommerce ul.products li.product h3,
	.woocommerce div.product .product_title,
	.woocommerce #content div.product .product_title,
	.woocommerce-page div.product .product_title,
	.woocommerce-page #content div.product .product_title,
	.woocommerce .related h2,
	.woocommerce .upsells h2,
	.woocommerce .cross-sells h2,
	.woocommerce .cart_totals h2,
	.woocommerce-thankyou-order-received,
	.work-details h4,
	.work-details h4 a,
	.entry-content .entry-post-title h2 a,
	ul.gridblock-listbox .work-details h4 a:hover,
	h2#comments,
	ol.commentlist li.comment .comment-author .fn,
	.entry-content .comment-reply-title,
	.comment-reply-title,
	h1.entry-title, .entry-coontent h1.entry-title,
	.search-results .entry-title > span
	';

	$style['page_general_font'] = '
	body,
	.section-description,
	.entry-title-subheading,
	.worktype-categories,
	.boxtitle-worktype,
	.sidebar-widget,
	.slideshow-box-categories,
	#password-protected p,
	.button-blog-continue,
	.readmore-service,
	.post-password-form p,
	.fullscreen-carousel .swiper-desc,
	.fullscreen-swiperslides .swiper-desc,
	.event-heading,
	.entry-content .pullquote-right,
	.entry-content .pullquote-left,
	.entry-content .pullquote-center,
	.entry-title-wrap h1,
	h2.project-heading,
	.footer-end-block h2.section-title,
	.skill-bar-percent,
	.gridblock-parallax-wrap h4.slideshow-box-title,
	.positionaware-button,
	.responsive-titles h3,
	.photowall-title,
	.proofing-client-title,
	.comment-reply-title,
	.hero-text-wrap .hero-title,
	.slideshow_title,
	h1.slideshow_title,
	.static_slideshow_title,
	.slideshow_caption,
	.static_slideshow_caption,
	.coverphoto-text-container .slideshow_title,
	.coverphoto-text-container .static_slideshow_title,
	.gridblock-grid-element .boxtitle-hover a,
	.mtheme-lightbox .lg-sub-html,
	.shortcode-box-title,
	ul.vertical_images .vertical-images-title,
	.dimmer-text,
	.mtheme-404-wrap .mtheme-404-error-message1,
	.imagebox-title,
	.site-maintenance-text,
	h1.entry-title,
	.entry-content h3.progressbar-title,
	.entry-content h1,
	.entry-content h2,
	.entry-content h3,
	.entry-content h4,
	.entry-content h5,
	.entry-content h6,
	h2.section-title,
	#gridblock-filters,
	.quote_say,
	.quote_author,
	.blog-timeline-month,
	.jp-title,
	.gridblock-parallax-wrap .slideshow-box-categories,
	.time-count-data,
	.client-say,
	.pricing-table,
	.boxtitle-hover,
	.project-info ul li,
	.slideshow-owl-title,
	.hero-text-wrap,
	#header-searchform #hs,
	.vertical-menu,
	.wpcf7-form p,
	.toggle-menu-list li a,
	.blog-details-section-inner,
	.minimal-menu,
	.simple-menu,
	.page-link,
	.pricing-wrap,
	.pricing-table .pricing-row,
	.search-instructions,
	.phototag-archive-list,
	.album-item-count,
	.pagination,
	.slideshow-box-title,
	.mtheme-events-heading,
	.site-maintenance-text,
	.no-comments,
	.swiper-title-bright,
	.shortcode-swiper-container .swiper-title,
	.fullscreen-carousel .swiper-title,
	.fullscreen-swiperslides .swiper-title,
	.twentytwenty-before-label:before,
	.twentytwenty-after-label:before,
	.horizontal-bottom-bar,
	.donutcounter-value,
	.work-details h4 a,
	.entry-content .pullquote-right,
	.entry-content .pullquote-left,
	.entry-content .pullquote-center,
	.woocommerce .related h2,
	.woocommerce .upsells h2,
	.woocommerce .cross-sells h2,
	#footer .sidebar-widget .widget > h3,
	.woocommerce ul.products li.product .woocommerce-loop-category__title,
	.woocommerce ul.products li.product .woocommerce-loop-product__title,
	.woocommerce-page h1.entry-title,
	.homemenu .sf-menu .mega-item .children-depth-0 h6,
	.person h4.staff-position,
	.blog-grid-element-content .work-details h4 a,
	.proofing-restricted,
	.woocommerce div.product .woocommerce-tabs ul.tabs li a,
	.woocommerce .woocommerce-breadcrumb,
	.entry-content .work-details h4,
	.mtheme-lightbox .lg-sub-html h4,
	.vertical-menu ul.mtree a,
	.simple-menu ul.mtree a,
	.header-is-simple .responsive-mobile-menu ul.mtree a,
	.entry-content h3.food-item-title,
	.food-list .food-purchase-item a,
	.food-purchase-item,
	.footer-fullscreen-wrap,
	h3.food-item-title,
	.dashboard-inner h3,
	.comment-reply-title small a,
	.entry-content .pricing-service p,
	.responsive-mobile-menu,
	.cart-elements,
	.cart-content-checkout,
	.woocommerce .button,
	.mtheme-woo-order-selected,
	.woocommerce-result-count,
	.mtheme-404-wrap h4,
	.summary-info,
	.postsummarywrap,
	.postsummarywrap a,
	.fotorama__caption__wrap,
	.post-single-tags,
	.post-single-tags a,
	.entry-content .notice-text,
	#gridblock-filters li a,
	.comment-meta,
	.mtheme-lightbox .lg-sub-html,
	.entry-content h3.reservation-subheading,
	.client-company,
	.client-name,
	.person .person-details h3,
	.timeline-list-event > h3,
	.portfolio-section-heading h2,
	.service-content h4,
	.service-content h4 a,
	.work-details h4,
	.woocommerce-page h1,
	.woocommerce-page h2,
	.woocommerce-page h3,
	.woocommerce-page h4,
	.woocommerce-page h5,
	.woocommerce-page h6,
	.fullscreen-fotorama .fotorama__caption__wrap h2,
	.woocommerce ul.products li.product h3,
	.woocommerce-page ul.products li.product h3,
	#copyright,
	.sidebar-widget h3,
	.callout h5,
	.entry-content .callout h5,
	.section-heading h5,
	.entry-content .section-heading h5,
	.multi-headlines-wrap h5,
	.entry-content .multi-headlines-wrap h5,
	.entry-content .multi-headlines-wrap,
	input,
	textarea,
	label,
	button,
	.entry-content .wp-block-button .wp-block-button__link,
	.hero-text-wrap .hero-subtitle,
	.entry-content .photocard-wrap-common .heading-block h3.photocard-subtitle,
	.callout h5,
	.entry-content .callout h5,
	.section-heading h5,
	.entry-content .section-heading h5,
	h2.entry-sub-title,
	.entry-content .photocard-subtitle,
	.entry-content h2.entry-sub-title,
	#password-protected input,
	.post-password-form input,
	#password-protected label,
	.woocommerce #respond input#submit.alt,
	.woocommerce a.button.alt,
	.woocommerce button.button.alt,
	.woocommerce input.button.alt,
	.mtheme-button,
	.cart-buttons,
	.entry-content h3.ui-accordion-header,
	.button-blog-continue a,
	.readmore-service a,
	.project-details-link h4 a,
	.homemenu .sf-menu .megamenu-textbox,
	.homemenu .sf-menu a,
	.homemenu .sf-menu .mega-item .children-depth-0 h6,
	.homemenu,
	.homemenu .sf-menu ul li a,
	.minimal-menu ul.mtree > li > a,
	.vertical-menu ul.mtree > li > a,
	.simple-menu ul.mtree > li > a,
	.responsive-mobile-menu ul.mtree > li > a,
	.food-notice,
	.entry-content .photocard-wrap-common .heading-block h3.photocard-subtitle,
	.hero-text-wrap .hero-subtitle,
	.entry-content .section-heading h5
	';

	$style['page_headings_font'] = '
	h1,
	h2,
	h3,
	h4,
	h5,
	h6,
	.entry-content h1,
	.entry-content h2,
	.entry-content h3,
	.entry-content h4,
	.entry-content h5,
	.entry-content h6,
	.entry-title-wrap h1,
	.time-count-data,
	.pricing-wrap,
	.entry-content .work-details h4,
	h2.section-title,
	.entry-content .section-heading h5,
	h1.entry-title,
	.woocommerce-page h1.entry-title,
	.woocommerce .related h2,
	.woocommerce ul.products li.product .woocommerce-loop-product__title,
	.entry-content h3.progressbar-title,
	.work-details h4 a,
	.work-details h4,
	.entry-content .slideshow-box-info h3.photocard-subtitle,
	.entry-content .gridblock-blog-parallax h3.photocard-subtitle,
	.proofing-client-title,
	.mtheme-404-wrap h4,
	.entry-content h3.reservation-subheading,
	.client-company,
	.client-name,
	.person .person-details h3,
	.timeline-list-event > h3,
	.portfolio-section-heading h2,
	.service-content h4,
	.service-content h4 a,
	.work-details h4,
	.woocommerce-page h1,
	.woocommerce-page h2,
	.woocommerce-page h3,
	.woocommerce-page h4,
	.woocommerce-page h5,
	.woocommerce-page h6,
	.fullscreen-fotorama .fotorama__caption__wrap h2,
	.woocommerce ul.products li.product h3,
	.woocommerce-page ul.products li.product h3,
	.sidebar-widget h3,
	.callout h5,
	.entry-content .callout h5,
	.section-heading h5,
	.entry-content .section-heading h5,
	.multi-headlines-wrap h5,
	.entry-content .multi-headlines-wrap h5,
	.entry-content .multi-headlines-wrap
	';

	$style['page_font_content'] = '
	.entry-content,
	input,
	textarea,
	label,
	button,
	.skill-bar-percent,
	.entry-content .wp-block-button .wp-block-button__link,
	.woocommerce .woocommerce-message,
	.woocommerce a.button.alt,
	#password-protected label,
	.mtheme-button,
	#copyright,
	.worktype-categories,
	.post-password-form p,
	#password-protected p,
	.sidebar-widget,
	.client-company,
	.client-name,
	.woocommerce ul.products li.product a,
	.woocommerce-page ul.products li.product a,
	ol.commentlist li.comment .comment-author .fn a,
	ol.commentlist li.comment .comment-author,
	#gridblock-filters li a:hover,
	#gridblock-filters li a,
	.woocommerce span.onsale,
	.woocommerce button.button.alt,
	.woocommerce .button,
	.woocommerce-page span.onsale,
	#gridblock-filters .griblock-filters-subcats a,
	#commentform .logged-in-as,
	.theme-hover-arrow,
	ol.commentlist li.comment .comment-meta a,
	.post-thumbnail-navigation-inner,
	.post-thumbnail-navigation-inner a,
	.postsummarywrap .post-single-meta,
	.postsummarywrap a,
	.gridblock-parallax-wrap .slideshow-box-categories,
	.proofing-content .event-details > li,
	.entry-content .about_paypal,
	.woocommerce-checkout .place-order .terms label,
	.woocommerce-checkout .place-order .terms label a,
	.text-is-bright .woocommerce form .form-row label,
	.woocommerce-page .text-is-bright form .form-row label,
	.woocommerce form .form-row label,
	.woocommerce-page form .form-row label,
	.gridblock-blog-parallax .photocard-title,
	.gridblock-blog-parallax .quote_author,
	.gridblock-blog-parallax .photocard-contents,
	.gridblock-blog-parallax .button-blog-continue,
	.entry-content .gridblock-blog-parallax h3.photocard-subtitle,
	.gridblock-blog-parallax .button-blog-continue a,
	.gridblock-blog-parallax .photocard-contents,
	.entry-title-subheading,
	.entry-title-subheading p,
	.text-is-dark .entry-title-subheading p,
	.section-description,
	.section-description p,
	.text-is-dark .section-description p,
	.entry-content .smaller-content,
	.entry-content,
	.woocommerce #tab-description p,
	.woocommerce .entry-summary div[itemprop="description"],
	.blog-details-section .the-month,
	.post-meta-time-archive,
	.gridblock-parallax-wrap .work-description,
	.gridblock-five .work-description,
	.gridblock-four .work-description,
	.gridblock-three .work-description,
	.gridblock-two .work-description,
	.gridblock-one .work-description,
	.slideshow-box-info .work-description,
	.events-summary-wrap,
	.post-thumbnail-desc,
	.gallery .gallery-caption,
	table th,
	.entry-content q:before,
	.entry-content q:after,
	.entry-content dt,
	.readmore_link a,
	.readmore_link a:hover,
	.entry-content a.read-more-link:hover,
	.slideshow-box-description,
	.slideshow-box-content,
	.slideshow-box-readmore,
	.slideshow-box-price,
	.slideshow-box-content .slideshow-box-categories a:hover,
	.entry-content .ui-tabs .ui-tabs-nav .ui-state-active a,
	.entry-content .ui-tabs .ui-tabs-nav .ui-state-active a:hover,
	.entry-content .text-is-bright .ui-tabs .ui-tabs-nav li a,
	.entry-content .ui-tabs .ui-tabs-nav li a:hover,
	.entry-content .ui-tabs .ui-tabs-nav li.ui-tabs-selected a,
	.entry-content .ui-tabs .ui-tabs-nav li.ui-state-disabled a,
	.entry-content .ui-tabs .ui-tabs-nav li.ui-state-processing a,
	.person-details a,
	.person-socials a,
	.text-is-dark .callout h2.callout-title,
	.pricing-table .pricing-row,
	.password-protected-icon,
	.post-single-tags,
	.post-single-tags a,
	.page-link,
	.blog-grid-element .summary-date,
	.summary-comment a,
	.summary-date,
	.post-single-meta a:hover,
	.woocommerce .entry-summary .amount,
	.navigation a:hover,
	.nav-previous a,
	.nav-next a,
	.nav-lightbox a,
	.quote_say,
	.quote_author,
	.entry-content .blogpost_readmore a:hover,
	.entry-content .portfolio-details-section-inner .project-info ul li,
	.entry-content .portfolio-details-section-inner .portfolio-details-wrap .post-like-count,
	.client-company a:hover,
	.client-say,
	.wpcf7-form p,
	.wpcf7-form input,
	.wpcf7-form textarea,
	.mtheme-404-wrap #searchform input,
	.woocommerce-product-rating .woocommerce-review-link,
	.woocommerce-MyAccount-content .woocommerce-Button.button,
	.woocommerce-orders-table .woocommerce-button.button,
	.woocommerce .track_order .button,
	.woocommerce a.button.wc-backward,
	.woocommerce a.add_to_cart_button,
	.woocommerce a.add_to_cart_button.added,
	.woocommerce div.product span.price,
	.woocommerce div.product p.price,
	.woocommerce #content div.product span.price,
	.woocommerce #content div.product p.price,
	.woocommerce-page div.product span.price,
	.woocommerce-page div.product p.price,
	.woocommerce-page #content div.product span.price,
	.woocommerce-page #content div.product p.price,
	.woocommerce ul.products li.product .price,
	.woocommerce-page ul.products li.product .price,
	.woocommerce ul.products li.product .price .from,
	.woocommerce-page ul.products li.product .price .from,
	.woocommerce ul.products li.product .price del,
	.woocommerce-page ul.products li.product .price del,
	.mtheme-woo-order-selected,
	.woocommerce .woocommerce-breadcrumb,
	.woocommerce .woocommerce-breadcrumb a,
	.woocommerce .woocommerce-breadcrumb a:hover,
	.woocommerce-result-count,
	.woocommerce table.shop_table th,
	.woocommerce-page table.shop_table th,
	.woocommerce .product_meta,
	.woocommerce div.product .woocommerce-tabs ul.tabs li a,
	.woocommerce .product_meta a,
	.woocommerce div.product .woocommerce-tabs ul.tabs li a,
	.woocommerce div.product .woocommerce-tabs ul.tabs li a:hover,
	.woocommerce div.product .woocommerce-tabs ul.tabs li,
	.woocommerce #content div.product .woocommerce-tabs ul.tabs li,
	.woocommerce-page div.product .woocommerce-tabs ul.tabs li,
	.woocommerce-page #content div.product .woocommerce-tabs ul.tabs li,
	.woocommerce div.product .woocommerce-tabs ul.tabs li.active,
	.woocommerce #content div.product .woocommerce-tabs ul.tabs li.active,
	.woocommerce-page div.product .woocommerce-tabs ul.tabs li.active,
	.woocommerce-page #content div.product .woocommerce-tabs ul.tabs li.active,
	.woocommerce .shop_table thead th,
	.woocommerce .shop_table th.product-name,
	.woocommerce .shop_table th.product-price,
	.woocommerce .shop_table th.product-quantity,
	.woocommerce .shop_table th.product-total,
	.woocommerce .shop_table th.product-subtotal,
	.woocommerce .shop_table .product-name,
	.woocommerce .shop_table .product-price,
	.woocommerce .shop_table .product-quantity,
	.woocommerce .shop_table .product-total,
	.woocommerce .shop_table .product-subtotal,
	.woocommerce table th,
	.woocommerce table td,
	.woocommerce form .form-row label,
	.woocommerce-page form .form-row label,
	.woocommerce #content div.product p.price del,
	.woocommerce #content div.product span.price del,
	.woocommerce div.product p.price del,
	.woocommerce div.product span.price del,
	.woocommerce-page #content div.product p.price del,
	.woocommerce-page #content div.product span.price del,
	.woocommerce-page div.product p.price del,
	.woocommerce-page div.product span.price del,
	.woocommerce table.shop_table tfoot td,
	.woocommerce table.shop_table tfoot th,
	.woocommerce-page table.shop_table tfoot td,
	.woocommerce-page table.shop_table tfoot th,
	.woocommerce #reviews #comments ol.commentlist li .meta,
	.woocommerce-checkout #payment ul.payment_methods li,
	.cart-elements .cart-title,
	.cart-content-checkout,
	.cart-view-link a,
	.cart-checkout-link a,
	.woocommerce-checkout .order_details,
	.client-position,
	.imagebox-content-above .imagebox-desc,
	.imagebox-content-below .imagebox-desc
	';

	$style['page_content'] = '
	.woocommerce ul.products li.product a,
	.woocommerce-page ul.products li.product a,
	ol.commentlist li.comment .comment-author .fn a,
	ol.commentlist li.comment .comment-author,
	#gridblock-filters li a:hover,
	#gridblock-filters li a,
	#gridblock-filters .griblock-filters-subcats a,
	#commentform .logged-in-as,
	.theme-hover-arrow,
	ol.commentlist li.comment .comment-meta a,
	.post-thumbnail-navigation-inner,
	.post-thumbnail-navigation-inner a,
	.postsummarywrap i,
	.postsummarywrap .post-single-meta,
	.postsummarywrap a,
	.gridblock-parallax-wrap .slideshow-box-categories,
	.proofing-content .event-details > li,
	.entry-content .about_paypal,
	.woocommerce-checkout .place-order .terms label,
	.woocommerce-checkout .place-order .terms label a,
	.text-is-bright .woocommerce form .form-row label,
	.woocommerce-page .text-is-bright form .form-row label,
	.woocommerce form .form-row label,
	.woocommerce-page form .form-row label,
	.gridblock-blog-parallax .photocard-title,
	.gridblock-blog-parallax .quote_author,
	.gridblock-blog-parallax .photocard-contents,
	.gridblock-blog-parallax .button-blog-continue,
	.entry-content .gridblock-blog-parallax h3.photocard-subtitle,
	.gridblock-blog-parallax .button-blog-continue a,
	.gridblock-blog-parallax .photocard-contents,
	.entry-title-subheading,
	.entry-title-subheading p,
	.text-is-dark .entry-title-subheading p,
	.section-description,
	.section-description p,
	.text-is-dark .section-description p,
	.entry-content .smaller-content,
	.entry-content,
	.woocommerce #tab-description p,
	.woocommerce .entry-summary div[itemprop="description"],
	.blog-details-section .the-month,
	.post-meta-time-archive,
	.gridblock-parallax-wrap .work-description,
	.gridblock-five .work-description,
	.gridblock-four .work-description,
	.gridblock-three .work-description,
	.gridblock-two .work-description,
	.gridblock-one .work-description,
	.slideshow-box-info .work-description,
	.events-summary-wrap,
	.post-thumbnail-desc,
	.gallery .gallery-caption,
	table th,
	.entry-content q:before,
	.entry-content q:after,
	.entry-content dt,
	.readmore_link a,
	.readmore_link a:hover,
	.entry-content a.read-more-link:hover,
	.slideshow-box-description,
	.slideshow-box-content,
	.slideshow-box-readmore,
	.slideshow-box-price,
	.slideshow-box-content .slideshow-box-categories a:hover,
	.entry-content .ui-tabs .ui-tabs-nav .ui-state-active a,
	.entry-content .ui-tabs .ui-tabs-nav .ui-state-active a:hover,
	.entry-content .text-is-bright .ui-tabs .ui-tabs-nav li a,
	.entry-content .ui-tabs .ui-tabs-nav li a:hover,
	.entry-content .ui-tabs .ui-tabs-nav li.ui-tabs-selected a,
	.entry-content .ui-tabs .ui-tabs-nav li.ui-state-disabled a,
	.entry-content .ui-tabs .ui-tabs-nav li.ui-state-processing a,
	.person-details a,
	.person i,
	.person-socials a,
	.text-is-dark .callout h2.callout-title,
	.pricing-row i,
	.pricing-tick-yes.pricing-row i,
	.pricing-table .pricing-row,
	.password-protected-icon,
	.post-single-tags,
	.post-single-tags a,
	.page-link,
	.blog-grid-element .summary-date,
	.summary-comment i,
	.summary-comment a,
	.summary-date,
	.post-single-meta a:hover,
	.woocommerce .entry-summary .amount,
	.navigation a:hover,
	.nav-previous a,
	.nav-next a,
	.nav-lightbox a,
	.quote_say,
	.quote_say i,
	.quote_author,
	.entry-content .blogpost_readmore a:hover,
	.entry-content .portfolio-details-section-inner .project-info ul li,
	.entry-content .portfolio-details-section-inner .project-details-link i,
	.entry-content .portfolio-details-section-inner .portfolio-details-wrap .post-like-count,
	.entry-content .portfolio-details-section-inner .portfolio-details-wrap .like-vote-icon i,
	.client-company a:hover,
	.client-say,
	.wpcf7-form p,
	.wpcf7-form input,
	.wpcf7-form textarea,
	.mtheme-404-wrap .mtheme-404-icon i,
	.mtheme-404-wrap #searchform input,
	.woocommerce-product-rating .woocommerce-review-link,
	.woocommerce-MyAccount-content .woocommerce-Button.button,
	.woocommerce-orders-table .woocommerce-button.button,
	.woocommerce .track_order .button,
	.woocommerce a.button.wc-backward,
	.woocommerce a.add_to_cart_button,
	.woocommerce a.add_to_cart_button.added,
	.woocommerce div.product span.price,
	.woocommerce div.product p.price,
	.woocommerce #content div.product span.price,
	.woocommerce #content div.product p.price,
	.woocommerce-page div.product span.price,
	.woocommerce-page div.product p.price,
	.woocommerce-page #content div.product span.price,
	.woocommerce-page #content div.product p.price,
	.woocommerce ul.products li.product .price,
	.woocommerce-page ul.products li.product .price,
	.woocommerce ul.products li.product .price .from,
	.woocommerce-page ul.products li.product .price .from,
	.woocommerce ul.products li.product .price del,
	.woocommerce-page ul.products li.product .price del,
	.mtheme-woo-order-selected,
	.mtheme-woo-order-selected-wrap i,
	.woocommerce .woocommerce-breadcrumb,
	.woocommerce .woocommerce-breadcrumb a,
	.woocommerce .woocommerce-breadcrumb a:hover,
	.woocommerce-result-count,
	.woocommerce table.shop_table th,
	.woocommerce-page table.shop_table th,
	.woocommerce .product_meta,
	.woocommerce div.product .woocommerce-tabs ul.tabs li a,
	.woocommerce .product_meta a,
	.woocommerce div.product .woocommerce-tabs ul.tabs li a,
	.woocommerce div.product .woocommerce-tabs ul.tabs li a:hover,
	.woocommerce div.product .woocommerce-tabs ul.tabs li,
	.woocommerce #content div.product .woocommerce-tabs ul.tabs li,
	.woocommerce-page div.product .woocommerce-tabs ul.tabs li,
	.woocommerce-page #content div.product .woocommerce-tabs ul.tabs li,
	.woocommerce div.product .woocommerce-tabs ul.tabs li.active,
	.woocommerce #content div.product .woocommerce-tabs ul.tabs li.active,
	.woocommerce-page div.product .woocommerce-tabs ul.tabs li.active,
	.woocommerce-page #content div.product .woocommerce-tabs ul.tabs li.active,
	.woocommerce .shop_table thead th,
	.woocommerce .shop_table th.product-name,
	.woocommerce .shop_table th.product-price,
	.woocommerce .shop_table th.product-quantity,
	.woocommerce .shop_table th.product-total,
	.woocommerce .shop_table th.product-subtotal,
	.woocommerce .shop_table .product-name,
	.woocommerce .shop_table .product-price,
	.woocommerce .shop_table .product-quantity,
	.woocommerce .shop_table .product-total,
	.woocommerce .shop_table .product-subtotal,
	.woocommerce table th,
	.woocommerce table td,
	.woocommerce form .form-row label,
	.woocommerce-page form .form-row label,
	.woocommerce #content div.product p.price del,
	.woocommerce #content div.product span.price del,
	.woocommerce div.product p.price del,
	.woocommerce div.product span.price del,
	.woocommerce-page #content div.product p.price del,
	.woocommerce-page #content div.product span.price del,
	.woocommerce-page div.product p.price del,
	.woocommerce-page div.product span.price del,
	.woocommerce table.shop_table tfoot td,
	.woocommerce table.shop_table tfoot th,
	.woocommerce-page table.shop_table tfoot td,
	.woocommerce-page table.shop_table tfoot th,
	.woocommerce #reviews #comments ol.commentlist li .meta,
	.woocommerce-checkout #payment ul.payment_methods li,
	.cart-elements .cart-title,
	.cart-content-checkout,
	.cart-view-link a,
	.cart-checkout-link a,
	.woocommerce-checkout .order_details,
	.client-position,
	.imagebox-content-above .imagebox-desc,
	.imagebox-content-below .imagebox-desc
	';

	$style['page_bordercolor'] = '
	table th,
	table td,
	.entry-content a.read-more-link:hover,
	.pagination-navigation a:hover,
	.pagination a:hover,
	.woocommerce nav.woocommerce-pagination ul li a:hover,
	.woocommerce nav.woocommerce-pagination ul li a:focus,
	.woocommerce nav.woocommerce-pagination ul li a:hover,
	.woocommerce nav.woocommerce-pagination ul li span.current
	';

	$style['page_backgroundcolor'] = '
	.page-link a:hover
	';

	return $style[ $get_class ];
}
